### ISSUE TITLE
run cricket/tests/gpu/checkpoint.sh get error

### ISSUE THREAD

**Issue by beyou923** [RWTH-ACS/cricket#1]
hello, I run the cricket/tests/gpu/checkpoint.sh script and get an error. like this:
 `0x00007ffff7ddc140 in _start () from /lib64/ld-linux-x86-64.so.2

[Inferior 1 (process 16963) detached]

04/20/22 15:06:25.475429 (DEBUG):       the command is 'kernel.testapp'

04/20/22 15:06:25.475654   DEBUG: using prog=-246232657, vers=674482919, derived from "/proc/self/exe"  in cpu-server.c(200)

04/20/22 15:06:25.475671 (INFO):        using TCP...

04/20/22 15:06:25.476136 (INFO):        listening on port 60942

04/20/22 15:06:25.476267 (DEBUG):       opening '/home/eiling/projects/cricket/tests/bin/kernel.testapp'

04/20/22 15:06:25.476433 (INFO):        found CUDA initialization function at 0x4018aa

04/20/22 15:06:25.476481 (INFO):        waiting for RPC requests...

server pid: 16963

client pid: 16983

04/20/22 15:06:27.138071 (INFO):        connection to host "localhost"

04/20/22 15:06:27.138345 (DEBUG):       the command is "kernel.testapp"

04/20/22 15:06:27.138356   DEBUG: using prog=-246232657, vers=674482919 in cpu-client.c(87)

04/20/22 15:06:27.138366 (INFO):        connecting via TCP...

04/20/22 15:06:27.139252 (INFO):        string: "hello"

04/20/22 15:06:27.142453 (DEBUG):       found kernel "_Z15kernel_no_paramv" [param_num: 0, param_size: -1445615080]

04/20/22 15:06:27.142590 (DEBUG):       found kernel "_Z6kernelPtS_S_csix" [param_num: 7, param_size: 40]

04/20/22 15:06:27.144101 (DEBUG):       child exit code: 0

04/20/22 15:06:27.144126   DEBUG: __cudaRegisterFatBinary       in cpu-client.c(270)

__cudaRegisterFunction(fatCubinHandle=(nil), hostFun=0x401812, devFunc=_Z15kernel_no_paramv, deviceName=_Z15kernel_no_paramv, thread_limit=-1, tid=[(nil)], bid=[(nil)], bDim=[(nil)], gDim=[(nil)], wSize=(nil))

04/20/22 15:06:27.144141   DEBUG: searching for _Z15kernel_no_paramv in 2 entries       in cpu-utils.c(193)

04/20/22 15:06:27.144147   DEBUG: _Z15kernel_no_paramv  in cpu-utils.c(198)

__cudaRegisterFunction(fatCubinHandle=(nil), hostFun=0x4016cd, devFunc=_Z6kernelPtS_S_csix, deviceName=_Z6kernelPtS_S_csix, thread_limit=-1, tid=[(nil)], bid=[(nil)], bDim=[(nil)], gDim=[(nil)], wSize=(nil))

04/20/22 15:06:27.144156   DEBUG: searching for _Z6kernelPtS_S_csix in 2 entries        in cpu-utils.c(193)

04/20/22 15:06:27.144161   DEBUG: _Z15kernel_no_paramv  in cpu-utils.c(198)

04/20/22 15:06:27.144166   DEBUG: _Z6kernelPtS_S_csix   in cpu-utils.c(198)

04/20/22 15:06:27.144234   DEBUG: cudaGetDeviceCount    in cpu-server-runtime.c(302)

elapsed time: 0.151057

found 1 devices

A[2048]={15183, 5909, 39324, 16294, 25624, 63281, 1133, 9314, 52216, 12031, 2445, 21597, 13509, 26926, 26717, 17449, 43697, 9177, 38203, 37564, 12105, 14935, 31848, 46153, 29089, 43698, 2093, 2036, 22994, 54249, 10114, 26076, ... }

x[64]={17933, 27638, 54613, 24189, 9017, 1175, 50149, 57193, 19645, 55487, 22299, 17105, 43083, 11672, 34953, 11345, 33499, 59732, 33792, 8338, 37813, 38540, 51229, 58687, 14390, 5712, 18699, 57188, 8470, 21585, 22370, 26403, }

About to initialize CUDA context...

04/20/22 15:06:27.295370   DEBUG: cudaMalloc    in cpu-server-runtime.c(1164)

dev_A = 0x7fff95e00000

CUDA context initialized

04/20/22 15:06:27.436070   DEBUG: cudaMalloc    in cpu-server-runtime.c(1164)

04/20/22 15:06:27.436169   DEBUG: cudaMalloc    in cpu-server-runtime.c(1164)

04/20/22 15:06:27.436273   DEBUG: cudaMalloc    in cpu-server-runtime.c(1164)

Mallocs done

04/20/22 15:06:27.436385   DEBUG: cudaMemcpyHtoD        in cpu-server-runtime.c(1326)

04/20/22 15:06:27.436531   DEBUG: cudaMemcpyHtoD        in cpu-server-runtime.c(1326)

04/20/22 15:06:27.436597   DEBUG: cudaMemcpyHtoD        in cpu-server-runtime.c(1326)

04/20/22 15:06:27.436660   DEBUG: cudaLaunchKernel(0x4016cd)    in cpu-client-runtime.c(936)

04/20/22 15:06:27.436684 (DEBUG):       calling kernel "_Z6kernelPtS_S_csix" (param_size: 40, param_num: 7)

04/20/22 15:06:27.436734   DEBUG: arg: 0x7fff95e00000 (-1780482048)     in cpu-server-runtime.c(850)

04/20/22 15:06:27.436745   DEBUG: arg: 0x7fff95e00800 (-1780480000)     in cpu-server-runtime.c(850)

04/20/22 15:06:27.436750   DEBUG: arg: 0x7fff95e00a00 (-1780479488)     in cpu-server-runtime.c(850)

04/20/22 15:06:27.436755   DEBUG: arg: (nil) (0)        in cpu-server-runtime.c(850)

04/20/22 15:06:27.436761   DEBUG: arg: (nil) (0)        in cpu-server-runtime.c(850)

04/20/22 15:06:27.436766   DEBUG: arg: (nil) (0)        in cpu-server-runtime.c(850)

04/20/22 15:06:27.436770   DEBUG: arg: (nil) (0)        in cpu-server-runtime.c(850)

04/20/22 15:06:27.436775   DEBUG: cudaLaunchKernel(func=0x4016cd, gridDim=[1,1,1], blockDim=[32,1,1], args=0xd625a0, sharedMem=0, stream=(nil))       in cpu-server-runtime.c(853)

04/20/22 15:06:27.439502   DEBUG: cudaLaunchKernel result: 0    in cpu-server-runtime.c(864)

Kernel Test: Create a checkpoint now!

04/20/22 15:06:27.439597   DEBUG: cudaDeviceSynchronize in cpu-server-runtime.c(287)

local still running: 0/128

local still running: 1/128

local still running: 2/128

local still running: 3/128

local still running: 4/128

local still running: 5/128

local still running: 6/128

local still running: 7/128

local still running: 8/128

local still running: 9/128

local still running: 10/128

local still running: 11/128

local still running: 12/128

local still running: 13/128

local still running: 14/128

local still running: 15/128

local still running: 16/128

local still running: 17/128

local still running: 18/128

criu doing

c1.sh: line 47: 16983 Killed                  LD_PRELOAD=${CRICKET_CLIENT}:/opt/cricket/bin/libtirpc.so ${CUDA_APP}

criu done

cricket checkpoint doing

[New LWP 16989]

[New LWP 16990]

[Thread debugging using libthread_db enabled]

Using host libthread_db library "/lib64/libthread_db.so.1".

0x00007ffff7ffa7c2 in clock_gettime ()

local still running: 19/128

local still running: 20/128

local still running: 21/128

[Detaching after fork from child process 17041]

04/20/22 15:06:30.558914 (DEBUG):       the command is 'cudbgprocess'

04/20/22 15:06:30.558961 (DEBUG):       skipping RPC server

Thread 1 "kernel.testapp" received signal SIGURG, Urgent I/O condition.

[Switching focus to CUDA kernel 0, grid 1, block (0,0,0), thread (0,0,0), device 0, sm 0, warp 0, lane 0]

0x0000000000d5d960 in kernel(unsigned short*, unsigned short*, unsigned short*, char, short, int, long long)<<<(1,1,1),(32,1,1)>>> ()

Cuda api initialized and attached!

got API

Device "Tesla V100-SXM2-16GB":

        index: 0

        type: "GV100GL-A"

        SM type: "sm_70"

        lanes: 32

        predicates 7

        registers: 256

        SMs: 80

        warps: 64

checkpointing kernel with name: "_Z6kernelPtS_S_csix"

stack-size: 336, param-addr: 352, param-size: 40, param-num: 7

SM 0: 1 - 0000000000000000000000000000000000000000000000000000000000000001

SM 0 warp 0 (active): 55555555 - 01010101010101010101010101010101

SM 0 warp 0 (valid): ffffffff - 11111111111111111111111111111111

04/20/22 15:06:30.811030   **ERROR: There is no room in the top level function (i.e. the kernel). This kernel can thus never be restored!       in /cricket-cr.c(835)**

cricket-checkpoint: could not make checkpointable.

local still running: 22/128

Thread 1 "kernel.testapp" received signal SIGURG, Urgent I/O condition.

0x00007ffff7ffa7c2 in clock_gettime ()

[Inferior 1 (process 16963) detached]

cricket done
`

how can i solve this problem?

**Comment by n-eiling** [comment]
Hi,

I haven't had the time to work on the checkpoint/restart code for quite some time. It is only tested with sm_61 devices, i.e., Tesla P100 and Tesla P4. For newer sm generations the SASS assembly changed quite a bit (more control codes, different machine code). Howerver, as newer devices can also run sm_61 code the example should work as cricket works mostly on the SASS assembly level.

I don't have access to a V100 device, however I was able to replicate your problem on T4 and A100 devices. The cause is probably that newer devices react differently to GDB commands (i.e. stepping through the kernel). 

Making the checkpoint/restart procedures work with newer generations is on my todo list. I will probably not work on V100 support, though.

Sorry, but for now I don't think it's possible to use checkpoint/restart on your device unless you want to modify the code yourself. A good starting point would be here: https://github.com/RWTH-ACS/cricket/blob/30eace1289ef9cc2240a1a73c7f2694b2308cd18/gpu/src/cricket-cr.c#L806

**Comment by beyou923** [comment]
> 

thanks, I will test it on other devices.
