### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by beyou923** [RWTH-ACS/cricket#2]
hi, I get the following error when compiling:
In file included from ../../gdb/python/py-arch.c:24:0:
../../gdb/python/python-internal.h:232:63: error: ‘PyObject* (* PyUnicode_FromFormat)(const char*, ...)’ redeclared as different kind of symbol
 extern PyObject * (*gdbpy_StringFromFormat) (const char *, ...);
                                                               ^
In file included from /root/anaconda3/include/python3.7m/Python.h:80:0,
                 from ../../gdb/python/python-internal.h:88,
                 from ../../gdb/python/py-arch.c:24:
/root/anaconda3/include/python3.7m/unicodeobject.h:879:24: error: previous declaration of ‘PyObject* PyUnicode_FromFormat(const char*, ...)’
 PyAPI_FUNC(PyObject *) PyUnicode_FromFormat(

How to solve this？

**Comment by n-eiling** [comment]
cuda-gdb seems to not like your python version. We don't really need python support anyways so I just deactivated it. Can you try again using the latest master?
