### ISSUE TITLE
Compile Error：invalid application of ‘sizeof’ to incomplete type ‘struct cudaArraySparseProperties’

### ISSUE THREAD

**Issue by beyou923** [RWTH-ACS/cricket#3]
hi, I get the following error when compiling:
...
make -C cpu
make[1]: Entering directory `/root/bihui/cricket/cpu'
rpcgen -C -M -N -c -o cpu_rpc_prot_xdr.c cpu_rpc_prot.x
rpcgen -C -M -N -h -o cpu_rpc_prot.h cpu_rpc_prot.x
gcc -std=gnu99 -I../submodules/libtirpc/install/include/tirpc -I/usr/local/cuda/include -c -fpic -o cpu_rpc_prot_xdr.o cpu_rpc_prot_xdr.c -L../submodules/libtirpc/install/lib -L/usr/local/cuda/lib64 -ltirpc -ldl -lcrypto
rpcgen -C -M -N -m -o cpu_rpc_prot_svc.c cpu_rpc_prot.x
./generate_dispatch.sh
gcc -std=gnu99 -I../submodules/libtirpc/install/include/tirpc -I/usr/local/cuda/include -c -fpic -o cpu_rpc_prot_svc_mod.o cpu_rpc_prot_svc_mod.c -L../submodules/libtirpc/install/lib -L/usr/local/cuda/lib64 -ltirpc -ldl -lcrypto
gcc -std=gnu99 -I../submodules/libtirpc/install/include/tirpc -I/usr/local/cuda/include -c -fpic -o cpu-server.o cpu-server.c -L../submodules/libtirpc/install/lib -L/usr/local/cuda/lib64 -ltirpc -ldl -lcrypto
gcc -std=gnu99 -I../submodules/libtirpc/install/include/tirpc -I/usr/local/cuda/include -c -fpic -o cpu-utils.o cpu-utils.c -L../submodules/libtirpc/install/lib -L/usr/local/cuda/lib64 -ltirpc -ldl -lcrypto
gcc -std=gnu99 -I../submodules/libtirpc/install/include/tirpc -I/usr/local/cuda/include -c -fpic -o cpu-server-runtime.o cpu-server-runtime.c -L../submodules/libtirpc/install/lib -L/usr/local/cuda/lib64 -ltirpc -ldl -lcrypto
cpu-server-runtime.c: In function ‘cuda_device_get_texture_lmw_1_svc’:
cpu-server-runtime.c:235:19: warning: implicit declaration of function ‘cudaDeviceGetTexture1DLinearMaxWidth’ [-Wimplicit-function-declaration]
     result->err = cudaDeviceGetTexture1DLinearMaxWidth(&result->u64_result_u.u64,
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cpu-server-runtime.c: In function ‘cuda_event_record_with_flags_1_svc’:
cpu-server-runtime.c:677:15: warning: implicit declaration of function ‘cudaEventRecordWithFlags’; did you mean ‘cudaEventCreateWithFlags’? [-Wimplicit-function-declaration]
     *result = cudaEventRecordWithFlags(
               ^~~~~~~~~~~~~~~~~~~~~~~~
               cudaEventCreateWithFlags
cpu-server-runtime.c: In function ‘cuda_array_get_sparse_properties_1_svc’:
cpu-server-runtime.c:931:14: error: invalid application of ‘sizeof’ to incomplete type ‘struct cudaArraySparseProperties’
       sizeof(struct cudaArraySparseProperties);
              ^~~~~~
cpu-server-runtime.c:933:14: error: invalid application of ‘sizeof’ to incomplete type ‘struct cudaArraySparseProperties’
       sizeof(struct cudaArraySparseProperties));
              ^~~~~~
cpu-server-runtime.c:936:19: warning: implicit declaration of function ‘cudaArrayGetSparseProperties’; did you mean ‘cuda_array_get_sparse_properties_1’? [-Wimplicit-function-declaration]
     result->err = cudaArrayGetSparseProperties(
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   cuda_array_get_sparse_properties_1
make[1]: *** [cpu-server-runtime.o] Error 1
make[1]: Leaving directory `/root/bihui/cricket/cpu'
make: *** [cpu] Error 2

How to solve this？

**Comment by beyou923** [comment]
my OS is Centos 7, gcc version is 7.3.0, CUDA Version: 11.2，Driver Version: 460.91.03 and nvcc version：V11.0.194

**Comment by n-eiling** [comment]
CUDA 11.2 should include the definition of this struct. I added an explicit include to the header file where it is defined. Can you try again with the latest master?

**Comment by beyou923** [comment]
I upgrade cuda version to 11.3, all problems are solved.
