### ISSUE TITLE
g++ goto statement: jump to label error

### ISSUE THREAD

**Issue by tddg** [RWTH-ACS/cricket#34]
Hello, 

Could you tell which g++ version you used for compiling cricket? 
We use g++ 9.4.0 (Ubuntu) but it complains the "error: jump to label" error on each "goto" statement. 

Thanks!

**Comment by zhuangqh** [comment]
I am using  8.5.0. It's ok

**Comment by Magnus1cheng** [comment]
Same error here. I'm using g++ 11.4

**Comment by n-eiling** [comment]
I fixed it by moving the declarations to the beginning of the function.
