### ISSUE TITLE
Intrinsic kernel issued error in CUDA 12 environment.

### ISSUE THREAD

**Issue by Magnus1cheng** [RWTH-ACS/cricket#38]
First of all, this is a great project, and I'm doing some experiments based on cricket in CUDA 12 environment. Thank you for all the contributions.
Recently, I got a error when I use `__dsqrt_rn()` intrinsic in my kernel.
Following is my error message:
```
+16:00:00.210589 ERROR: section .nv.info.__internal_7_ not found        in cpu-elf2.c:687
+16:00:00.210594 ERROR: get_parm_for_kernel failed for kernel $__internal_7_$__cuda_sm20_dsqrt_rn_f64_mediumpath_v1     in cpu-elf2.c:984
+16:00:00.210597 ERROR: error getting parameter info    in cpu-elf2.c:508
+16:00:00.210598 ERROR: error getting fatbin info       in cpu-client.c:366
```

I dive a little, found that it's because `__dsqrt_rn` would create symbol `$__internal_7_$__cuda_sm20_dsqrt_rn_f64_mediumpath_v1` under `.nv.info` section, just like a noinline device function. But there's no section like `.nv.info.__internal_7.......`, seems like my nvcc only create section with prefix `.nv.info` for `__global__` function, but not for cuda intrinsic or device function.
This issue is caused by https://github.com/RWTH-ACS/cricket/blob/master/cpu/cpu-elf2.c#L636

My current workaround is to pass the `get_parm_for_kernel` function in cpu-elf2.c for kernel name start with `$`, like in line https://github.com/RWTH-ACS/cricket/blob/master/cpu/cpu-elf2.c#L983
```
        if((ki->name)[0]!='$'){
            if (get_parm_for_kernel(elf, ki, memory, memsize) != 0) {
                LOGE(LOG_ERROR, "get_parm_for_kernel failed for kernel %s", kernel_str);
                goto cleanup;
            }
        }
```
but I'm not sure if this is reasonable, because I'm new to this project, and I don't know if it's okay when we have no parameter information for cuda intrinsic. But after this workaround, my code works anyway. 

So, I'm now sure if this is caused by the elf file format in newer version of NVCC. Or it's caused by any other reasons. I don't have another CUDA env.

Following is my CUDA codes:
```
#include <stdio.h>

#define TYPE double
__device__ void my_func(TYPE* a) {
        atomicAdd(a, 1);
        __syncthreads();
}
__global__ void cuda_hello(TYPE* a){
        //printf("Hello World from GPU!\n");
        *a = 99.0;
        atomicAdd(a, 1);
        *a = __dsqrt_rn(*a);
        my_func(a);
         //__syncthreads();
}

int main() {
        printf("Hellow World from CPU\n");
        TYPE *a;
        TYPE *d_a;
        a = (TYPE*)malloc(sizeof(TYPE) * 1);
        *a = 0;
        printf("before: %f\n", *a);
        cudaMalloc((void**)&d_a, sizeof(TYPE) * 1);
        cudaMemcpy(d_a, a, sizeof(TYPE) * 1, cudaMemcpyHostToDevice);

        printf("-----launching kernel----\n");
        cuda_hello<<<1,1>>>(d_a);
        cudaMemcpy(a, d_a, sizeof(TYPE) * 1, cudaMemcpyDeviceToHost);

        printf("after: %f\n", *a);
        return 0;
}
```

**Comment by n-eiling** [comment]
Thanks for your detailed issue. I fixed it a bit differently than you suggested. Sorry for the delay.
