### ISSUE TITLE
Execute the test program and report an error: result incorrect!

### ISSUE THREAD

**Issue by beyou923** [RWTH-ACS/cricket#4]
I executed the following command on my machine and got an error.( Machine configuration：Centos 7 / kernel : 3.10.0-693.2.2.el7.x86_64 / CUDA-11.3 / NVIDIA Tesla P100 )

$ LD_PROLOAD=/root/bihui/cricket/bin/cricket-server.so /root/bihui/cricket/tests/test_apps/kernel.testapp
elapsed time: 0.294615
found 1 devices
A[2048]={15183, 5909, 39324, 16294, 25624, 63281, 1133, 9314, 52216, 12031, 2445, 21597, 13509, 26926, 26717, 17449, 43697, 9177, 38203, 37564, 12105, 14935, 31848, 46153, 29089, 43698, 2093, 2036, 22994, 54249, 10114, 26076, ... }
x[64]={17933, 27638, 54613, 24189, 9017, 1175, 50149, 57193, 19645, 55487, 22299, 17105, 43083, 11672, 34953, 11345, 33499, 59732, 33792, 8338, 37813, 38540, 51229, 58687, 14390, 5712, 18699, 57188, 8470, 21585, 22370, 26403, }
About to initialize CUDA context...
dev_A = 0x7f6a5e800000
CUDA context initialized
Mallocs done
Kernel Test: Create a checkpoint now!
dev_res: 0x7f6a5e800a00
continuing
Result:
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
mismatch: res[0]=0 != expected_result[0]=41184
mismatch: res[1]=0 != expected_result[1]=11744
mismatch: res[2]=0 != expected_result[2]=60768
mismatch: res[3]=0 != expected_result[3]=1760
mismatch: res[4]=0 != expected_result[4]=60896
mismatch: res[5]=0 != expected_result[5]=4832
mismatch: res[6]=0 != expected_result[6]=61792
mismatch: res[7]=0 != expected_result[7]=49376
mismatch: res[8]=0 != expected_result[8]=45920
mismatch: res[9]=0 != expected_result[9]=30176
mismatch: res[10]=0 != expected_result[10]=41312
mismatch: res[11]=0 != expected_result[11]=42336
mismatch: res[12]=0 != expected_result[12]=14432
mismatch: res[13]=0 != expected_result[13]=53088
mismatch: res[14]=0 != expected_result[14]=50016
mismatch: res[15]=0 != expected_result[15]=4576
mismatch: res[16]=0 != expected_result[16]=63456
mismatch: res[17]=0 != expected_result[17]=2016
mismatch: res[18]=0 != expected_result[18]=23008
mismatch: res[19]=0 != expected_result[19]=46944
mismatch: res[20]=0 != expected_result[20]=25824
mismatch: res[21]=0 != expected_result[21]=18016
mismatch: res[22]=0 != expected_result[22]=34016
mismatch: res[23]=0 != expected_result[23]=48480
mismatch: res[24]=0 != expected_result[24]=37984
mismatch: res[25]=0 != expected_result[25]=26976
mismatch: res[26]=0 != expected_result[26]=64992
mismatch: res[27]=0 != expected_result[27]=51424
mismatch: res[28]=0 != expected_result[28]=51040
mismatch: res[29]=0 != expected_result[29]=55904
mismatch: res[30]=0 != expected_result[30]=20576
mismatch: res[31]=0 != expected_result[31]=42336
---> result incorrect!
elapsed time: 0.090015

**Comment by n-eiling** [comment]
You need to start the server like this:
```
LD_PRELOAD=/root/bihui/cricket/bin/cricket-server.so /root/bihui/cricket/tests/test_apps/kernel.testapp
```
which should output
```
05/10/22 15:18:45.967385 (INFO):	using TCP...
05/10/22 15:18:45.967610 (INFO):	listening on port 57450
05/10/22 15:18:45.967864 (INFO):	found CUDA initialization function at 0x40192d
05/10/22 15:18:45.967889 (INFO):	waiting for RPC requests...
```

and then start the client in a separate shell:
`REMOTE_GPU_ADDRESS=127.0.0.1 LD_PRELOAD=/root/bihui/cricket/bin/cricket-client.so /root/bihui/cricket/tests/test_apps/kernel.testapp`

**Comment by beyou923** [comment]
> 

When I start the client program, the following information is output：

[root@p100 bin]# REMOTE_GPU_ADDRESS=127.0.0.1 LD_PRELOAD=/root/bihui/cricket/bin/cricket-client.so /root/bihui/cricket/tests/test_apps/kernel.testapp
05/11/22 10:12:22.185465 (INFO):        connection to host "127.0.0.1"
05/11/22 10:12:22.185756 (DEBUG):       the command is "kernel.testapp"
05/11/22 10:12:22.185770   DEBUG: using prog=1449306678, vers=570542772 in cpu-client.c(88)
05/11/22 10:12:22.185780 (INFO):        connecting via TCP...
05/11/22 10:12:22.187960 (DEBUG):       found kernel "_Z15kernel_no_paramv" [param_num: 0, param_size: -2046141512]
05/11/22 10:12:22.188082 (DEBUG):       found kernel "_Z6kernelPtS_S_csix" [param_num: 7, param_size: 40]
05/11/22 10:12:22.189384 (DEBUG):       child exit code: 0
05/11/22 10:12:22.189412   DEBUG: __cudaRegisterFatBinary       in cpu-client.c(272)
__cudaRegisterFunction(fatCubinHandle=(nil), hostFun=0x401812, devFunc=_Z15kernel_no_paramv, deviceName=_Z15kernel_no_paramv, thread_limit=-1, tid=[(nil)], bid=[(nil)], bDim=[(nil)], gDim=[(nil)], wSize=(nil))
05/11/22 10:12:22.189426   DEBUG: searching for _Z15kernel_no_paramv in 2 entries       in cpu-utils.c(193)
05/11/22 10:12:22.189433   DEBUG: _Z15kernel_no_paramv  in cpu-utils.c(198)
__cudaRegisterFunction(fatCubinHandle=(nil), hostFun=0x4016cd, devFunc=_Z6kernelPtS_S_csix, deviceName=_Z6kernelPtS_S_csix, thread_limit=-1, tid=[(nil)], bid=[(nil)], bDim=[(nil)], gDim=[(nil)], wSize=(nil))
05/11/22 10:12:22.189440   DEBUG: searching for _Z6kernelPtS_S_csix in 2 entries        in cpu-utils.c(193)
05/11/22 10:12:22.189445   DEBUG: _Z15kernel_no_paramv  in cpu-utils.c(198)
05/11/22 10:12:22.189449   DEBUG: _Z6kernelPtS_S_csix   in cpu-utils.c(198)
elapsed time: 0.290862
found 1 devices
A[2048]={15183, 5909, 39324, 16294, 25624, 63281, 1133, 9314, 52216, 12031, 2445, 21597, 13509, 26926, 26717, 17449, 43697, 9177, 38203, 37564, 12105, 14935, 31848, 46153, 29089, 43698, 2093, 2036, 22994, 54249, 10114, 26076, ... }
x[64]={17933, 27638, 54613, 24189, 9017, 1175, 50149, 57193, 19645, 55487, 22299, 17105, 43083, 11672, 34953, 11345, 33499, 59732, 33792, 8338, 37813, 38540, 51229, 58687, 14390, 5712, 18699, 57188, 8470, 21585, 22370, 26403, }
About to initialize CUDA context...
dev_A = 0x7f136a800000
CUDA context initialized
Mallocs done
05/11/22 10:12:22.569149   DEBUG: cudaLaunchKernel(0x4016cd)    in cpu-client-runtime.c(936)
05/11/22 10:12:22.569172 (DEBUG):       calling kernel "_Z6kernelPtS_S_csix" (param_size: 40, param_num: 7)
Kernel Test: Create a checkpoint now!
dev_res: 0x7f136a800a00
continuing
Result:
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
mismatch: res[0]=0 != expected_result[0]=41184
mismatch: res[1]=0 != expected_result[1]=11744
mismatch: res[2]=0 != expected_result[2]=60768
mismatch: res[3]=0 != expected_result[3]=1760
mismatch: res[4]=0 != expected_result[4]=60896
mismatch: res[5]=0 != expected_result[5]=4832
mismatch: res[6]=0 != expected_result[6]=61792
mismatch: res[7]=0 != expected_result[7]=49376
mismatch: res[8]=0 != expected_result[8]=45920
mismatch: res[9]=0 != expected_result[9]=30176
mismatch: res[10]=0 != expected_result[10]=41312
mismatch: res[11]=0 != expected_result[11]=42336
mismatch: res[12]=0 != expected_result[12]=14432
mismatch: res[13]=0 != expected_result[13]=53088
mismatch: res[14]=0 != expected_result[14]=50016
mismatch: res[15]=0 != expected_result[15]=4576
mismatch: res[16]=0 != expected_result[16]=63456
mismatch: res[17]=0 != expected_result[17]=2016
mismatch: res[18]=0 != expected_result[18]=23008
mismatch: res[19]=0 != expected_result[19]=46944
mismatch: res[20]=0 != expected_result[20]=25824
mismatch: res[21]=0 != expected_result[21]=18016
mismatch: res[22]=0 != expected_result[22]=34016
mismatch: res[23]=0 != expected_result[23]=48480
mismatch: res[24]=0 != expected_result[24]=37984
mismatch: res[25]=0 != expected_result[25]=26976
mismatch: res[26]=0 != expected_result[26]=64992
mismatch: res[27]=0 != expected_result[27]=51424
mismatch: res[28]=0 != expected_result[28]=51040
mismatch: res[29]=0 != expected_result[29]=55904
mismatch: res[30]=0 != expected_result[30]=20576
mismatch: res[31]=0 != expected_result[31]=42336
---> result incorrect!
elapsed time: 0.089449
05/11/22 10:12:22.569868 (INFO):        api-call-cnt: 14
05/11/22 10:12:22.569881 (INFO):        memcpy-cnt: 4224

**Comment by n-eiling** [comment]
It seems like the kernel is not properly executed. Are you able to run it without cricket, i.e., running just `/root/bihui/cricket/tests/test_apps/kernel.testapp`?

**Comment by beyou923** [comment]
> 

The result is still the same: result incorrect!

**Comment by n-eiling** [comment]
This does not seem to be an issue with cricket. The example program works for me on different architectures and GPUs so I am not sure whats wrong here.
Do other GPU applications work for you, e.g., the matrix multiplication example from CUDA? Try with and without cricket.
