### ISSUE TITLE
clinet error: Port mapper failure unable to receive:errno 111 connection refused

### ISSUE THREAD

**Issue by freshduer** [RWTH-ACS/cricket#44]
my server and client are in the same machine

and both in docker container

![image](https://github.com/RWTH-ACS/cricket/assets/72605280/2facd2ea-8ded-4e9b-bca7-6dad28cd4736)

**Comment by GYDmedwin** [comment]
@freshduer Hi, I also encountered the same problem in Docker. How did you solve it? THANKS！

**Comment by freshduer** [comment]
> @freshduer Hi, I also encountered the same problem in Docker. How did you solve it? THANKS！

do not use these things in docker
