### ISSUE TITLE
Failed to run test program

### ISSUE THREAD

**Issue by leeyiding** [RWTH-ACS/cricket#45]
Hello, I have compiled successfully, but an error occurred when running the test program. I need your help.

CUDA version: 11.8
cuDNN version: 8.9.03

server `./bin/cricket-rpc-server`
```
welcome to cricket!
+08:00:00.000003 INFO:  using TCP...
+08:00:00.000967 INFO:  listening on port 56951
+08:00:00.121489 INFO:  waiting for RPC requests...
+08:00:08.068937 INFO:  string: "hello"

+08:00:08.070386 ERROR: cuModuleLoadData failed: 209    in cpu-server-driver.c:47
+08:00:08.070760 ERROR: (nil) not found in resource manager - we cannot call a function from an unknown module. in cpu-server-driver.c:115
+08:00:08.071011 INFO:  RPC deinit requested.
```

client: `REMOTE_GPU_ADDRESS=127.0.0.1 LD_PRELOAD=./bin/cricket-client.so ./bin/tests/kernel.testapp`
```
+08:00:00.000007 INFO:  connection to host "127.0.0.1"
+08:00:00.000364 INFO:  connecting via TCP...
+08:00:00.003835 ERROR: error registering fatbin: 209   in cpu-client.c:380
+08:00:00.004118 ERROR: error registering function: -1  in cpu-client.c:344
+08:00:00.004158 WARNING: fatCubinHandle is NULL - so we have nothing to unload. (This is okay if this binary does not contain a kernel.)in cpu-client.c:398
+08:00:00.004376 INFO:  api-call-cnt: 0
+08:00:00.004409 INFO:  memcpy-cnt: 0
```

When I compile and test on two servers, I get the same error. Is there any solution for this situation? Thank you so much

**Comment by n-eiling** [comment]
You are getting CUDA error 209. The description of this error is

>cudaErrorNoKernelImageForDevice = 209
>    This indicates that there is no kernel image available that is suitable for the device. This can occur when a user specifies code generation options for a particular CUDA source file that do not include the corresponding device configuration.

What GPU are you using? You might have to modify [this](https://github.com/RWTH-ACS/cricket/blob/ce8fdf7d4f4df696cf65c6d35926a76443d18f28/tests/test_apps/Makefile#L8) line to your supported GPU architecture.

**Comment by leeyiding** [comment]
Thank you very much for your answer. I am using Tesla V100 and Tesla T4. After changing `ARCH` to `sm_70` and `sm_75` respectively according to your method, this problem was successfully solved. 👍
