### ISSUE TITLE
build error in ubuntu 22.04

### ISSUE THREAD

**Issue by xvim** [RWTH-ACS/cricket#50]
In file included from cpu-client-cudnn.c:5:
cpu-client-cudnn.c:1345:55: error: unknown type name ‘cudnnAlgorithmDescriptor_t’; did you mean ‘cudnnAttnDescriptor_t’?
 1345 | DEF_FN(cudnnStatus_t, cudnnCreateAlgorithmDescriptor, cudnnAlgorithmDescriptor_t *, algoDesc)

https://docs.nvidia.com/deeplearning/cudnn/archives/cudnn-820/api/index.html

[3.2.7. cudnnCreateAlgorithmDescriptor()](https://docs.nvidia.com/deeplearning/cudnn/archives/cudnn-820/api/index.html#cudnnCreateAlgorithmDescriptor)
This function has been deprecated in cuDNN 8.0.

**Comment by alexfrolov** [comment]
Hi!

I have been able to build Cricket on Ubuntu 22.04:

* cudnn-linux-x86_64-8.9.7.29_cuda12-archive
* cudnn-linux-x86_64-8.9.7.29_cuda11-archivet with 

Best,  Alex
