### ISSUE TITLE
Async memory operation

### ISSUE THREAD

**Issue by Forsworns** [RWTH-ACS/cricket#54]
how do you deal with API like `cuMemcpyAsync` in a client-server manner? I cannot find the related logics in the source code, it is not supported?

**Comment by n-eiling** [comment]
`cuMemcpyAsync` is currently not implemented (see https://github.com/RWTH-ACS/cricket/blob/ce8fdf7d4f4df696cf65c6d35926a76443d18f28/cpu/cpu-client-driver.c#L606)
'cudaMemcpyAsync' currently forwards to 'cudaMemcpy' and ignores the stream parameter (https://github.com/RWTH-ACS/cricket/blob/ce8fdf7d4f4df696cf65c6d35926a76443d18f28/cpu/cpu-client-runtime.c#L1727).
Implementing this correctly should be pretty straight forward though.

**Comment by Forsworns** [comment]
Thanks, got it :)
