### ISSUE TITLE
Question about cuda test samples

### ISSUE THREAD

**Issue by freeliuzc** [RWTH-ACS/cricket#9]
Firstly, thank you for awesome project! 
I have some doubts about cuda sample. In the first sample ` LD_PRELOAD=/opt/cricket/bin/cricket-server.so /opt/cricket/tests/test_kernel`, you start server by test_kernel. However, I cant find any info about test_kernel. Is it a general refer 
 for any test cases or we can get it in other ways？

**Comment by n-eiling** [comment]
test_kernel is built by the Makefile in [tests/test_apps](https://github.com/RWTH-ACS/cricket/tree/master/tests/test_apps). It runs a simply matrix multiplication.
